### ISSUE TITLE
Question: How to effectively learn Data Structures and Algorithms

### ISSUE THREAD

**Issue by reputationabhi** [karngyan/karngyan#1]
Bhaiya according to you from where we can brush up/ revise  our DS and Algo Skills for CP? Basically how to effectively learn DS & Algorithms. If you can provide a **blog** or an **article** upon that it will be much better. 😄

**Comment by karngyan** [comment]
Hey @reputationabhi 

So, if you're a beginner (Zero K about DSA). 

1. I'd recommend you start exploring. And by exploring I mean just google and youtube it a lot.
2. Once you have explored, watched a few videos, may read a few articles, now you know what awaits you.
3. It's time to learn those topics and find the best resources that suit your learning pattern.
4. If algorithms intrigue you, go ahead and start competing with the best on codeforces and maybe, make it a hobby.
5. If you want to get better at it, it's all about practice, practice, practice.

Here's a list of non-exhaustive resources for step 3 some of which I still look up to sometimes for DSA.

- [Competitive Programming: From Beginner to Expert](https://www.commonlounge.com/discussion/5d2822257dfa49328d85fd27cf114441)
- [Introduction to Programming in C](https://nptel.ac.in/courses/106/104/106104128/)
- [Errichto](https://www.youtube.com/channel/UCBr_Fu6q9iHYQCh13jmpbrg)
- [MIT OCW: Design and Analysis of Algorithms](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-046j-design-and-analysis-of-algorithms-spring-2015/lecture-videos/)
- [Competitive Programmer’s Handbook by Antti Laaksonen](https://cses.fi/book/book.pdf)
- [IARCS - Study Material](https://www.iarcs.org.in/inoi/online-study-material/)

You can find a few more links [here](https://notes.karngyan.com/did-you-have-a-look-at-x/competitive-programming)

Happy Coding! 👍 

PS. Remember to close the issue if this satisfies you. 🔢

**Comment by reputationabhi** [comment]
Thankyou Soo Much for your Reply... I'll follow up what you've mentioned. 
Have a Great Day @karngyan
