### ISSUE TITLE
C++ or Python

### ISSUE THREAD

**Issue by basukrishna1** [karngyan/karngyan#2]
someone who is new to coding.. should start with which language C++ or Python? BCS nowadays Python has become trending where as C++ is losing its popularity and use ..

**Comment by karngyan** [comment]
Hey @basukrishna1 

I'll give you a mediocre Indian student perspective on this. 

- If you're in your high school, Python is easier to pick up and understand. You can write a bunch of scripts to automate stuff and maybe pick up some web development with Flask/Django.

- If you're in college, I'd recommend C before C++ and then Python or maybe Java. This phase of life is the most important part of a learner, so go deep, learn, and enjoy computer science to your fullest. This is the time you get your basics strong.

- If you're a professional in the field of computer science engineering and you don't know C, I'm sorry but I'll wash my hands if I ever shake hands with you. 🤝 🧼 

Although in no way, this categorization applies for everybody. Sometimes people learn C/C++ in their high school and then picking up Python or any other Programming Language is just a child's play. 

What I'm trying to say is I don't believe in what's trending. If you study biology, you don't just become a cardiologist at once. First, you need to understand how a cell works.

Happy Coding! 😄 

PS. Remember to close the issue if this satisfies you. 🔢
